### ISSUE TITLE
Add optional CSS build for using without Bootstrap [enhancement]

### ISSUE THREAD

**Issue by Haprog** [sliptree/bootstrap-tokenfield#156]
Even though it is cool that Tokenfield is designed for usage with Bootstrap it would be even better if there was an easy option to use it also without Bootstrap since Tokenfield doesn't really depend that much on Bootstrap (it only uses a little portion of the Bootstrap CSS to look great).

I suggest that you include an optional CSS file in this project that adds some basic styles for using this so that Tokenfield looks the same (or almost the same) even without Bootstrap.

For example put these in `less/bootstrap-tokenfield-nobs.less` then you could build it so that `dist/css/bootstrap-tokenfield-nobs.css` would include first the "nobs" styles and also the normal bootstrap-tokenfield styles. And also make a minified version of it. Then users that don't use Bootstrap would just use that alternate CSS build instead of the normal bootstrap-tokenfield.css.

Here is example CSS (to use instead of bootstrap.css) to make Tokenfield look good even without the whole Bootstrap CSS:

``` css
.tokenfield,
.tokenfield *,
.tokenfield *:before,
.tokenfield *:after {
    -webkit-box-sizing: border-box;
       -moz-box-sizing: border-box;
            box-sizing: border-box;
}

.tokenfield {
    font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    font-size: 14px;
    line-height: 1.428571429;
    color: #555;

    display: block;
    width: 100%;
    padding: 6px 12px;
    vertical-align: middle;
    background-color: #fff;
    border: 1px solid #ccc;
    border-radius: 4px;

    -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,0.075);
            box-shadow: inset 0 1px 1px rgba(0,0,0,0.075);
    -webkit-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
            transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
}

.tokenfield .token .close {
    font-weight: bold;
    color: #000;
    text-shadow: 0 1px 0 #fff;
    opacity: .2;
    filter: alpha(opacity=20);
    text-decoration: none;
}

.tokenfield .token .close:hover,
.tokenfield .token .close:focus {
    cursor: pointer;
    opacity: .5;
    filter: alpha(opacity=50);
}

.tokenfield .token-input {
    margin: 0;
    font-family: inherit;
    font-size: inherit;
    line-height: inherit;
}
```

This makes it look like a Bootstrap input. Though you may want to adjust these styles to make it look like a more generic/native input instead if you don't want to get the "Bootstrap look" with this alternate CSS, but atleast include some simple borders and paddings/margins.

With this included the only real dependency of bootstrap-tokenfield would be jQuery.
