### ISSUE TITLE
input, hint, and suggestions are misaligned with Bootstrap-sass

### ISSUE THREAD

**Issue by dimroc** [sliptree/bootstrap-tokenfield#182]
I had to customize the css to get everything lined up properly. Details below:

``` scss
$token-height: 21px;

.tokenfield {
  input.token-input.tt-hint {
    height: $token-height;
    border: 0px;
  }

  input.token-input.tt-input {
    height: $token-height;
    position: absolute !important;
    top: 0px;
    left: 0px;
    padding-left: 0px;
  }

  .tt-dropdown-menu {
    top: $token-height !important;
  }
}
```

https://gist.github.com/dimroc/bd0dc95d0b1106ae42db
