### ISSUE TITLE
Option to get rid of max-width on token-label

### ISSUE THREAD

**Issue by agladysh** [sliptree/bootstrap-tokenfield#206]
My tokens absolutely must be displayed in full. How do I forbid the tokenfield from setting max-width on my token-labels?

**Comment by agladysh** [comment]
NB: Here is an ugly workaround I use now:

```css
.tokenfield .token .token-label
{
  max-width: 10000px !important;
}
```
