### ISSUE TITLE
tokenfield-typeahead.css needs vertical-align

### ISSUE THREAD

**Issue by powerman** [sliptree/bootstrap-tokenfield#53]
You set `.twitter-typeahead` to `display: inline-block` and this result in some side-effects (for example, extra margin below input noticeable in multiline `.form-horizontal` configured to have no space between rows with inputs using `.form-group {margin-bottom: 0;}`).

Anyway, it's recommended to always use inline-block with vertical-align:

``` css
.twitter-typeahead {
  vertical-align: top;
}
```
