### ISSUE TITLE
token-input padding

### ISSUE THREAD

**Issue by a-ivanov81** [sliptree/bootstrap-tokenfield#72]
I'm set:

``` css
.tokenfield.form-control .token-input {
    padding-left: 5px;
}
```

and now tokent-input always on new line.
I think you need add input padding values to width calculate.

Thanks for excellent work!
